### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by mattcorr** [DevOrg11/backendcore#5]
Since there isn't an open PR, I'll put my comments in here: :)

## General
- Add a .gitignore file to the repo root. Ensure it filters out files from your obj folder. 
*You don't need to include obj or bin folders in your repo.*
- Add a **README.md** file to the repo root and put in details about your repo. 
*Details like how to build/test the solution and any pre-reqs etc.*
- you might want to consider putting the projects into a `/src/` sub folder more to make the repo root more cleaner.

## EF code
- the actual EF code looks fine to me, its pretty early stages at the moment, but all the classes are straight forward and easy to understand.

**Comment by Aslam2k** [comment]
Hey @mattcorr , I have updated the folder structure and created a README.md which needs updating
